### ISSUE TITLE
Bounds on iteration appear hard-coded for nDim=2, quadtree implementation

### ISSUE THREAD

**Issue by smakolski** [vasturiano/d3-force-magnetic#2]
https://github.com/vasturiano/d3-force-magnetic/blob/8a6fe1c296133a9329493eba60eb35c21f9ca739/src/magnetic.js#L106

shouldn't this be more like `i < nDim*nDim` instead of `i < 4`?

**Comment by vasturiano** [comment]
@smakolski good catch, I think you're right!
I think it should be `2 ** nDim` though, not `nDim * nDim`.
I'll patch it when I have a moment. 👍

**Comment by smakolski** [comment]
Thanks! (Both for the update as well as the prolific amount of great d3 stuff in general!)
